title: Didaktik der Informatik PH & HSE Heidelberg
description: Projektwebseite für die Didaktik der Informatik PH Heidelberg
theme: jekyll-theme-minimal
navigation:
  - title: Über uns
    url: /about
  - title: Projekte
    url: /projects
  - title: Materialien
    url: /materials
  - title: Publikationen
    url: /publications
